name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: install python2
      run: sudo apt install -y python2
    - name: test
      run: python2 test.py
    - name: rundb
      run: ./rundb
